using System.Runtime.InteropServices;

namespace SageBinaryData;

public enum ObjectStatusType
{
    DESTROYED,
    CAN_ATTACK,
    UNDER_CONSTRUCTION,
    UNSELECTABLE,
    NO_COLLISIONS,
    NO_ATTACK,
    NO_SPECIAL_ABILITY,
    AIRBORNE_TARGET,
    PARACHUTING,
    REPULSOR,
    SKIP_PATH_CLAMPING,
    AFLAME,
    BURNED,
    CANNOT_BE_SOLD,
    IS_FIRING_WEAPON,
    IS_RELOADING_WEAPON,
    IS_BRAKING,
    STEALTHED,
    HIDDEN,
    DETECTED,
    CAN_STEALTH,
    SOLD,
    UNDERGOING_REPAIR,
    RECONSTRUCTING,
    IS_ATTACKING,
    NO_AUTO_ACQUIRE,
    USING_ABILITY,
    IS_AIMING_WEAPON,
    NO_ATTACK_FROM_AI,
    IGNORING_STEALTH,
    IS_MELEE_ATTACKING,
    FOLLOWING_THROUGH,
    LEASHED_RETURNING,
    DEATH_1,
    DEATH_2,
    DEATH_3,
    DEATH_4,
    DEATH_5,
    CONTESTED,
    CONTESTING_BUILDING,
    HORDE_MEMBER,
    TRANSPORT_MOVING_TO_CONTAIN,
    RIDER_IS_PILOT,
    DAMAGED,
    REALLYDAMAGED,
    RUBBLE,
    IRRADIATED,
    NO_SHADOW,
    IN_STASIS,
    OUT_OF_PHASE,
    NEXT_MOVE_IS_REVERSE,
    IMMOBILE,
    IMMOBILE_ALLOW_ROTATE,
    PAUSING,
    FLEE_OFF_MAP,
    NOT_IN_WORLD,
    INAUDIBLE,
    AIRBORNE_PULLED_FROM_SKY,
    ENRAGED,
    SINKING,
    RAMPAGING,
    INSIDE_GARRISON,
    DEPLOYED,
    UNATTACKABLE,
    ENCLOSED,
    TEMPORARILY_DEFECTED,
    TAGGED,
    DEPLOYING,
    TOPPLING,
    PORTER_TAGGED,
    NO_SQUISHCOLLIDE_DELAY,
    STAND_GROUND,
    UNCONTROLLABLY_SCARED,
    SPECIAL_ABILITY_PACKING_UNPACKING_OR_USING,
    DYNAMICS_SIMULATION_ACTIVE,
    UPDATING_AI,
    CLONED,
    IGNORE_AI_COMMAND,
    RUNNING_DOWN_FROM_BEHIND,
    DO_NOT_SCORE,
    CAN_NOT_WALK_ON,
    MARCH_OF_DEATH,
    DO_NOT_PICK_ME,
    INHERITED_FROM_ALLY_TEAM,
    SWITCHED_WEAPONS,
    END_FIRE_STATE,
    BOOKENDING,
    GENERIC_TOGGLE_STATE,
    CAN_CONTEST_GARRISON,
    BUILD_BEING_CANCELED,
    PENDING_CONSTRUCTION,
    PHANTOM_STRUCTURE,
    IN_FORMATION_TEMPLATE,
    IS_LEAVING_FACTORY,
    MOVING_TO_DISMOUNT,
    NO_HERO_PROPERTIES,
    CAN_ENTER_ANYTHING,
    ENTERING_GOAL,
    CHARGING_BASE_DEFENSES,
    INVISIBLE_DETECTED_BY_FRIEND,
    INVISIBLE_DETECTED,
    SHRUNK,
    ATTACHED,
    WONT_RIDE_WITH_YOU,
    COMMAND_BUTTON_TOGGLED,
    OCLMONITOR_COMPLETED_TASK,
    OCLMONITOR_MONITOR_RELEASED,
    USER_POWERED_DOWN,
    GARRISONED,
    BOOBY_TRAPPED,
    IS_HIDEOUT,
    EXECUTING_STORED_COMMAND,
    UNIT_WANTS_TO_REGARRISON,
    IN_COVER,
    DONT_CLEAR_FOR_BUILD,
    MATCH_TARGETS_SPEED,
    HAS_TIBERIUM_GROWTH_MOD,
    DYNAMICS_DISABLED,
    STEAL_NEXT_UNIT_TRAPPED,
    DOES_CONTAIN_TIBERIUM,
    IS_BEING_HARVESTED,
    NO_REFUND,
    SHIELDBODY_ENABLED,
    HEALTH_PERCENT_0,
    HEALTH_PERCENT_25,
    HEALTH_PERCENT_50,
    HEALTH_PERCENT_75,
    HEALTH_PERCENT_100,
    WEAPON_UPGRADED_01,
    WEAPON_UPGRADED_02,
    WEAPON_UPGRADED_03,
    COMBINED_PARENT,
    COMBINED_CHILD,
    COMBINED_ATTACHED,
    LOADED_FROM_MAP,
    ATTACKING_GARRISONED_STRUCTURE,
    EXITING_COMBINED,
    DELAYED_ENTER_STRUCTURE,
    DOCKING,
    HARVESTING,
    BRIDGE_IMPASSABLE,
    POWERED_DOWN_EMP,
    FORCE_ATTACKING,
    FORCE_ATTACK_MOVING,
    SCARED_CIVILIAN_CAR,
    USER_PARALYZED,
    BOOBY_TRAP_EXPLODE,
    IS_ENGAGED,
    CARRYING_FLAG,
    IS_MOVING_TO_RALLY_POINT,
    SPECIAL_ARMOR_ACTIVE,
    AIRCRAFT_IGNORE_SAMEPLAYER_HANGAR_RULE,
    NEXT_MOVE_IS_FORCE_ATTACK_MOVE,
    SPECIALABILITY_ACTIVE,
    CAN_STEALTH_FROM_PRODUCER,
    GARRISON_CAN_STEALTH,
    CAN_ATTACK_WHILE_STEALTHED,
    RESET_GOAL_POSITION,
    RIFT_OCCUPIED,
    WATER_LOCOMOTOR_ACTIVE,
    GROUND_LOCOMOTOR_ACTIVE,
    AIR_LOCOMOTOR_ACTIVE,
    UNPACKING,
    OVER_WATER,
    CONTAINER_OCCUPIED,
    PLACED_BY_PLAYER,
    DEFLECT_INCOMING_FIRE,
    DEPART_FROM_BOARDING,
    WAITING_FOR_BOARDING,
    HAS_SECONDARY_DAMAGE,
    IS_BEING_DRAGGED,
    CLEARED_FOR_LANDING,
    VEHICLE_ATTACHED,
    PARKED_AT_AIRFIELD,
    IN_SHIELD_SPHERE,
    HIT_SHIELD_SPHERE,
    NON_AUTOACQUIRABLE,
    CHARGING_WEAPON,
    OVERCHARGING_WEAPON,
    ENABLE_TRACER_DRAW,
    PREEMPT_PRE_ATTACK,
    LINE_SEGMENT_DAMAGE_ACTIVE,
    ADVANCED_MISSILE_PACKS,
    LEECHED_TARGET_ACTIVE,
    PLAYER_POWER_1,
    PLAYER_POWER_2,
    PLAYER_POWER_3,
    PLAYER_POWER_4,
    PLAYER_POWER_5,
    GRAPPLE_UPDATE_ACTIVE,
    SHROUD_REVEAL_TO_ALL,
    SURFACED,
    SUBMERGED,
    SKIRMISH_AI_DO_NOT_ATTACK,
    SKIRMISH_AI_DO_NOT_TAKE,
    TRANSFORMATION_TOGGLE_STATE,
    REPAIR_ALLIES_WHEN_IDLE,
    DO_NOT_AVOID_TALLBUILDING,
    ABSORBED_DAMAGE,
    NO_BRIBE,
    IGNORING_POWER_DOWN,
    EXCEEDED_PATH_NEIGHBOR_COUNT,
    CANNOT_LAND_AT_AIRFIELD,
    WALL_SEGMENT,
    IMMUNE_TO_BARK,
    UNDER_RUSH_ATTACK,
    UNDER_FROZEN,
    LANDING_IN_PROGRESS,
    UNDER_IRON_CURTAIN,
    EXPLOSIVES_ATTACHED,
    EXPLOSIVES_DETONATING,
    LIFTED_INTO_AIR,
    IN_NANOHIVE,
    SURFACED_IMMOBILE,
    BROADCASTING_INVISIBILITY,
    SCRAMBLED,
    MAGNETIZED,
    RIOT_SHIELDED,
    POINT_DEFENSE_DRONE_ATTACHED,
    GRAPPLE_UPDATE_BEING_MOVED,
    TARGETED_FOR_REPAIR,
    IN_SPIDER_HOLE,
    ANTI_GARRISON,
    BLATTED,
    BLAT_TRIGGER,
    REFLECTING,
    DESOLATION_ACTIVE,
    OPEN,
    SPECIAL_POWER_SELECTED,
    BRIDGE_DEAD
}

[StructLayout(LayoutKind.Sequential)]
public struct ObjectStatusBitFlags
{
    public const int Count = 230;
    public const int BitsInSpan = 32;
    public const int NumSpans = (Count + (BitsInSpan - 1)) / BitsInSpan;

    public unsafe fixed uint Value[NumSpans];
}

public enum DeathType
{
    NONE,
    NORMAL,
    CRUSHED,
    BURNED,
    EXPLODED,
    POISONED,
    TOPPLED,
    FLOODED,
    SUICIDED,
    LASERED,
    DETONATED,
    SPLATTED,
    POISONED_BETA,
    EXTRA_2,
    EXTRA_3,
    EXTRA_4,
    EXTRA_5,
    EXTRA_6,
    EXTRA_7,
    EXTRA_8,
    KNOCKBACK,
    SUPERNATURAL,
    FADED,
    SLAUGHTERED,
    CATALYST
}

[StructLayout(LayoutKind.Sequential)]
public struct DeathBitFlags
{
    public const int Count = 25;
    public const int BitsInSpan = 32;
    public const int NumSpans = (Count + (BitsInSpan - 1)) / BitsInSpan;

    public unsafe fixed uint Value[NumSpans];
}

[StructLayout(LayoutKind.Sequential)]
public struct DamageBitFlags
{
#if VERSION7
    public const int Count = 39;
#elif TIBERIUMWARS
    public const int Count = 34;
#elif KANESWRATH
    public const int Count = 37;
#endif
    public const int BitsInSpan = 32;
    public const int NumSpans = (Count + (BitsInSpan - 1)) / BitsInSpan;

    public unsafe fixed uint Value[NumSpans];
}

public enum DamageSubType
{
    NORMAL,
    BECOME_UNDEAD,
    SELF,
    UNDEFINED
}

public enum InvisibilityType
{
    INVALID = -1,
    STEALTH,
    CAMOUFLAGE
}

public enum InvisibilityNuggetOptions
{
    ALLOW_NEAR_TREES,
    DETECTED_BY_FRIENDLIES,
    DISCONTINUE_WHEN_REVEALED,
    UNTOGGLE_HIDDEN_WHEN_LEAVING_STEALTH
}

[StructLayout(LayoutKind.Sequential)]
public struct InvisibilityNuggetOptionsBitFlags
{
    public const int Count = 4;
    public const int BitsInSpan = 32;
    public const int NumSpans = (Count + (BitsInSpan - 1)) / BitsInSpan;

    public unsafe fixed uint Value[NumSpans];
}
